services:
  - type: web
    name: consulta-tjms
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATAJUD_API_KEY
        value: cDZHYzlZa0JadVREZDJCendQbXY6SkJlTzNjLV9TRENyQk1RdnFKZGRQdw==
      - key: EPROC_1G_URL
        value: https://eproc1g.tjms.jus.br/eproc
      - key: EPROC_2G_URL
        value: https://eproc2g.tjms.jus.br/eproc
